#!/usr/bin/env node
/**
 * Bundle the GitHub Action into a single committed file.
 *
 * A JavaScript action runs whatever is in the repository at the tag the user
 * pinned - there is no install step. Bundling everything (including the one
 * runtime dependency) means a workflow that pins `@v1` executes exactly the
 * code that was reviewed at that tag, with nothing fetched at run time.
 */
import { build } from 'esbuild';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const outfile = path.join(root, 'action', 'dist', 'index.js');

fs.rmSync(path.join(root, 'action', 'dist'), { recursive: true, force: true });

const result = await build({
  entryPoints: [path.join(root, 'src', 'action', 'main.ts')],
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node24',
  outfile,
  minify: false,
  sourcemap: false,
  legalComments: 'inline',
  banner: {
    js: [
      '// AI Shipcheck GitHub Action - generated by scripts/build-action.mjs.',
      '// Do not edit this file by hand; edit src/action/ and run `npm run build:action`.',
      "import { createRequire as __shipcheckCreateRequire } from 'node:module';",
      'const require = __shipcheckCreateRequire(import.meta.url);',
    ].join('\n'),
  },
  metafile: true,
});

const bytes = fs.statSync(outfile).size;
const inputs = Object.keys(
  result.metafile.outputs[path.relative(root, outfile)]?.inputs ?? {},
).length;
console.log(
  `Bundled action: action/dist/index.js (${(bytes / 1024).toFixed(0)} KB from ${inputs} modules)`,
);
